name: introduction-to-machine-learning-2024-kqlssl-mkdocs

services:
  mkdocs:
    container_name: kqlssl-container
    image: kamk/kqlssl-diary:latest
    build:
      context: .
      dockerfile: docs.Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./docs:/docs
    working_dir: /docs
    command: ["serve", "--dev-addr=0.0.0.0:8000", "--watch=docs"]
